development:
  adapter: mysql
  database: rafflr_development
  username: root
  password: mgd2nite
  host: localhost

test:
  adapter: mysql
  database: rafflr_test
  username: rafflr
  password: rafflr
  host: localhost

production:
  adapter: mysql
  database: rafflr
  username: rafflr
  password: xxxxxx 
  host: mysql.rafflr.com
